{
  config,
  pkgs,
  ...
}:
{
  # Set nvim as system editor
  environment.sessionVariables = {
    EDITOR = "nvim";
  };

  # Install neovim globally
  environment.systemPackages = with pkgs; [
    neovim
  ];

  home-manager.users.${config.username} =
    {
      config,
      pkgs,
      ...
    }:
    {
      xdg.configFile = {
        "nvim" = {
          source = ./config;
          recursive = true;
        };

        # Generate colors.lua from stylix base16 colors
        "nvim/lua/colors.lua".text = ''
          -- Auto-generated by NixOS from stylix configuration
          -- Do not edit directly - modify modules/common/theme.nix instead
          return {
            base00 = "${config.lib.stylix.colors.withHashtag.base00}", -- Default Background
            base01 = "${config.lib.stylix.colors.withHashtag.base01}", -- Lighter Background (status bars)
            base02 = "${config.lib.stylix.colors.withHashtag.base02}", -- Selection Background
            base03 = "${config.lib.stylix.colors.withHashtag.base03}", -- Comments, Invisibles, Line Highlighting
            base04 = "${config.lib.stylix.colors.withHashtag.base04}", -- Dark Foreground (status bars)
            base05 = "${config.lib.stylix.colors.withHashtag.base05}", -- Default Foreground, Caret, Delimiters, Operators
            base06 = "${config.lib.stylix.colors.withHashtag.base06}", -- Light Foreground (not often used)
            base07 = "${config.lib.stylix.colors.withHashtag.base07}", -- Light Background (not often used)
            base08 = "${config.lib.stylix.colors.withHashtag.base08}", -- Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
            base09 = "${config.lib.stylix.colors.withHashtag.base09}", -- Integers, Boolean, Constants, XML Attributes, Markup Link Url
            base0A = "${config.lib.stylix.colors.withHashtag.base0A}", -- Classes, Markup Bold, Search Text Background
            base0B = "${config.lib.stylix.colors.withHashtag.base0B}", -- Strings, Inherited Class, Markup Code, Diff Inserted
            base0C = "${config.lib.stylix.colors.withHashtag.base0C}", -- Support, Regular Expressions, Escape Characters, Markup Quotes
            base0D = "${config.lib.stylix.colors.withHashtag.base0D}", -- Functions, Methods, Attribute IDs, Headings
            base0E = "${config.lib.stylix.colors.withHashtag.base0E}", -- Keywords, Storage, Selector, Markup Italic, Diff Changed
            base0F = "${config.lib.stylix.colors.withHashtag.base0F}", -- Deprecated, Opening/Closing Embedded Language Tags
          }
        '';
      };
      home.packages = with pkgs; [
        # Neovim essentials
        tree-sitter
        sqlite

        # Formatters
        stylua
        nixpkgs-fmt
        nodePackages.prettier
        black
        isort
        shfmt

        # Linters
        markdownlint-cli2
        shellcheck
        nodePackages.eslint

        # LSP servers
        lua-language-server
        nil # Nix LSP
        nodePackages.typescript-language-server
        nodePackages.bash-language-server
        python312Packages.python-lsp-server
        yaml-language-server
        vscode-langservers-extracted # HTML, CSS, JSON, ESLint
        unstable.tofu-ls
        unstable.opentofu
        unstable.terraform-ls
        marksman # markdown
        mdx-language-server # mdx
      ];
    };
}
