# Development shell, formatter, and pre-commit checks
{
  nixpkgs,
  self,
  inputs,
  agenix-rekey,
  bun2nix,
}:
system:
let
  pkgs = import nixpkgs {
    inherit system;
    overlays = [
      agenix-rekey.overlays.default
      (_: _: { bun2nix-cli = bun2nix.packages.${system}.default; })
    ];
  };
  hcloud-upload-image = pkgs.callPackage ../packages/hcloud-upload-image.nix { };
  nixfmt = pkgs.treefmt.withConfig {
    runtimeInputs = [ pkgs.nixfmt-rfc-style ];

    settings = {
      # Log level for files treefmt won't format
      on-unmatched = "info";

      # Configure nixfmt for .nix files
      formatter.nixfmt = {
        command = "nixfmt";
        includes = [ "*.nix" ];
      };
    };
  };
  checkBunVersions = pkgs.writeShellApplication {
    name = "check-bun-versions";
    runtimeInputs = [
      pkgs.jaq
      pkgs.findutils
      pkgs.gawk
    ];
    text = builtins.readFile ./check-bun-versions.sh;
  };
  listMachines = pkgs.writeShellApplication {
    name = "list-machines";
    runtimeInputs = [ pkgs.jaq ];
    text = builtins.readFile ./list-machines.sh;
  };
  flashInstaller = pkgs.writeShellApplication {
    name = "flash-installer";
    runtimeInputs = [
      pkgs.jaq
      pkgs.util-linux
      pkgs.openssl
      pkgs.rage
      pkgs.pv
      pkgs.dosfstools
      listMachines
    ];
    text = builtins.readFile ./flash-installer.sh;
  };
  generateHostKey = pkgs.writeShellApplication {
    name = "generate-host-key";
    runtimeInputs = [
      pkgs.jaq
      pkgs.rage
      pkgs.openssh
      pkgs.agenix-rekey
      listMachines
    ];
    text = builtins.readFile ./generate-host-key.sh;
  };
  updateHostKey = pkgs.writeShellApplication {
    name = "update-host-key";
    runtimeInputs = [
      pkgs.rage
      pkgs.hostname
    ];
    text = builtins.readFile ./update-host-key.sh;
  };
  createSecret = pkgs.writeShellApplication {
    name = "create-secret";
    runtimeInputs = [
      pkgs.rage
      pkgs.gnugrep
      pkgs.agenix-rekey
    ];
    text = builtins.readFile ./create-secret.sh;
  };
  generateSyncthingKey = pkgs.writeShellApplication {
    name = "generate-syncthing-key";
    runtimeInputs = [
      pkgs.syncthing
      pkgs.jaq
      pkgs.rage
      pkgs.gnugrep
      pkgs.agenix-rekey
      listMachines
    ];
    text = builtins.readFile ./generate-syncthing-key.sh;
  };
  ntScripts =
    builtins.map
      (
        name:
        pkgs.writeShellApplication {
          inherit name;
          text = builtins.readFile (./. + "/${name}.sh");
        }
      )
      [
        "nt-syntax"
        "nt-eval"
        "nt-dry"
        "nt-pkg"
        "nt-option"
        "nt-build"
        "nt-check"
        "nt-hosts"
      ];
  # Pre-fetch bun dependencies for every TypeScript project in the repo so the
  # type-check and lint hooks can run `bun install` without network access
  # inside the Nix sandbox.  Add a new entry here whenever a new bun.nix is
  # added (either at the repo root or under modules/).
  bunDepsProjects = [
    (pkgs.bun2nix-cli.fetchBunDeps {
      bunNix = ../../bun.nix;
    })
    (pkgs.bun2nix-cli.fetchBunDeps {
      bunNix = ../../modules/common/mitmproxy-credential-proxy/proxy/bun.nix;
    })
    (pkgs.bun2nix-cli.fetchBunDeps {
      bunNix = ../../modules/common/llm-tools/llm-summarize/bun.nix;
    })
  ];
  # Merge all project caches into a single directory tree so we can pass one
  # path to BUN_DEPS_CACHE_DIR instead of a list.
  mergedBunDepsCache = pkgs.symlinkJoin {
    name = "merged-bun-cache";
    paths = map (d: "${d}/share/bun-cache") bunDepsProjects;
  };
  checkBunTypecheck = pkgs.writeShellApplication {
    name = "check-bun-typecheck";
    runtimeInputs = [
      pkgs.bun
      pkgs.typescript
    ];
    text = builtins.readFile ./check-bun-typecheck.sh;
    # Provide the pre-fetched cache so bun install can run offline in the Nix
    # sandbox.  The script copies it to a writable temp dir before use.
    runtimeEnv = {
      BUN_DEPS_CACHE_DIR = mergedBunDepsCache;
    };
  };
  checkBunEslint = pkgs.writeShellApplication {
    name = "check-bun-eslint";
    runtimeInputs = [ pkgs.bun ];
    text = builtins.readFile ./check-bun-eslint.sh;
    # Same offline cache as the typecheck hook.
    runtimeEnv = {
      BUN_DEPS_CACHE_DIR = mergedBunDepsCache;
    };
  };
in
{
  checks = {
    pre-commit-check = inputs.git-hooks.lib.${system}.run {
      src = self;
      hooks = {
        nixfmt-rfc-style.enable = true;
        statix.enable = true;
        deadnix = {
          enable = true;
          settings = {
            # bun.nix files are auto-generated by bun2nix and may contain
            # unused lambda pattern names (copyPathToStore, fetchFromGitHub,
            # fetchgit) for lockfiles that have no workspace/git dependencies.
            # Disabling the lambda pattern name check avoids false positives on
            # generated files without weakening the check on hand-written code.
            noLambdaPatternNames = true;
          };
        };
        gitleaks = {
          enable = true;
          name = "gitleaks";
          # Use protect mode to only scan staged changes, not full history
          entry = "${pkgs.gitleaks}/bin/gitleaks protect --staged -v --config ${../../gitleaks.toml}";
        };
        check-bun-versions = {
          enable = true;
          name = "check-bun-versions";
          entry = "${checkBunVersions}/bin/check-bun-versions";
          files = "package\\.json$";
          pass_filenames = false;
        };
        check-bun-typecheck = {
          enable = true;
          name = "check-bun-typecheck";
          entry = "${checkBunTypecheck}/bin/check-bun-typecheck";
          files = "\\.(ts|tsx)$";
          pass_filenames = true;
        };
        check-bun-eslint = {
          enable = true;
          name = "check-bun-eslint";
          entry = "${checkBunEslint}/bin/check-bun-eslint";
          files = "\\.(ts|tsx)$";
          pass_filenames = true;
        };
      };
    };
  };

  formatter = nixfmt;
  devShell = pkgs.mkShell {
    packages = [
      nixfmt
      pkgs.agenix-rekey
      pkgs.age
      pkgs.gitleaks
      (pkgs.writeShellScriptBin "headscale" ''
        export HEADSCALE_CLI_ADDRESS="headscale.panfactumcf.com:443"
        export HEADSCALE_CLI_API_KEY
        HEADSCALE_CLI_API_KEY=$(cat /run/agenix/headscale-api-key)
        TMPCONF=$(mktemp --suffix=.yaml)
        trap 'rm -f "$TMPCONF"' EXIT
        exec ${pkgs.headscale}/bin/headscale -c "$TMPCONF" "$@"
      '')
      pkgs.hcloud
      hcloud-upload-image
      listMachines
      flashInstaller
      generateHostKey
      updateHostKey
      generateSyncthingKey
      createSecret
    ]
    ++ ntScripts
    ++ self.checks.${system}.pre-commit-check.enabledPackages;

    inherit (self.checks.${system}.pre-commit-check) shellHook;
  };
}
