# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.kernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "zfs"
    "amdgpu"
  ];
  boot.kernelModules = [
    "kvm-amd"

    # Virtual Camera, included below
    "v4l2loopback"

    # Virtual Microphone, built-in
    "snd-aloop"

    # Monitoring device sensors
    "k10temp"
    "nct6775"
    "i2c-piix4"
    "lm92"
  ];
  boot.extraModulePackages = [

    # Use this to provide a virtual video sync in OBS
    config.boot.kernelPackages.v4l2loopback.out
  ];

  # Enable thermal monitoring
  environment.etc."sysconfig/lm_sensors".text = ''
    HWMON_MODULES="k10temp nct6775 i2c-piix4 lm92"
  '';

  boot.extraModprobeConfig = ''
    # exclusive_caps: Skype, Zoom, Teams etc. will only show device when actually streaming
    # card_label: Name of virtual camera, how it'll show up in Skype, Zoom, Teams
    # https://github.com/umlaeute/v4l2loopback
    options v4l2loopback exclusive_caps=1 card_label="Virtual Camera"
  '';

  ######################################
  ## Scanners
  ######################################
  # Scanning driver for Brother scanners (brother no longer provides the default version in nixpkgs)
  nixpkgs.overlays = [
    (self: super: {
      brscan5 = pkgs.unstable.brscan5;
    })
  ];
  hardware.sane = {
    enable = true;
    brscan5.enable = true;
  };
  services.saned.enable = true;
  services.avahi.enable = true;
  services.avahi.nssmdns = true;

  fileSystems."/" =
    {
      device = "primary/nixos/root";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "primary/nixos/home";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    {
      device = "primary/nixos/nix-store";
      fsType = "zfs";
    };

  fileSystems."/nix/var/nix/db" =
    {
      device = "primary/nixos/nix-db";
      fsType = "zfs";
    };

  fileSystems."/tmp" =
    {
      device = "primary/nixos/tmp";
      fsType = "zfs";
    };

  fileSystems."/home/jack/media" =
    {
      device = "secondary/encrypted/media";
      fsType = "zfs";
    };

  fileSystems."/nix/var/log" =
    {
      device = "secondary/encrypted/logs/nix";
      fsType = "zfs";
    };

  # We set "nofail" for the boot drives, b/c we don't want a drive failure to prevent
  # us from booting.
  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/3103-B6F3";
      fsType = "vfat";
      options = [ "nofail" ];
    };

  fileSystems."/boot1" =
    {
      device = "/dev/disk/by-uuid/3182-4B71";
      fsType = "vfat";
      options = [ "nofail" ];
    };


  # Again, "nofail" as these are not critical
  swapDevices =
    [{
      device = "/dev/disk/by-partuuid/5c7ca6b5-ddd8-9442-b94e-e3eb55d8ca20";
      randomEncryption = true;
      options = [ "nofail" ];
    }
      {
        device = "/dev/disk/by-partuuid/5ad84ba3-013c-084b-9685-02f979ac5dd0";
        randomEncryption = true;
        options = [ "nofail" ];
      }];

  hardware.cpu.amd.updateMicrocode = true;
  powerManagement.cpuFreqGovernor = "performance";
}
