return {
  {
    "neovim/nvim-lspconfig",
    ---@class PluginLspOpts
    opts = {
      ---@type lspconfig.options
      servers = {
        -- pyright will be automatically installed with mason and loaded with lspconfig
        pyright = {},
        terraformls = {},
        lua_ls = {},
        tsserver = {},
        rnix = {},
        eslint = {},
      },
    },
  },
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      highlight = { enable = true },
      ensure_installed = {
        "starlark",
        "python",
        "nix",
        "bash",
        "bibtex",
        "c",
        "cmake",
        "comment",
        "cpp",
        "css",
        "diff",
        "dockerfile",
        "dot",
        "fish", 
        "git_rebase",
        "gitignore",
        "gitattributes",
        "gitcommit",
        "go",
        "gomod",
        "gosum",
        "graphql",
        "html",
        "http",
        "java",
        "javascript",
        "jq",
        "jsdoc",
        "json",
        "json5",
        "latex",
        "lua",
        "mermaid",
        "passwd",
        "perl",
        "php",
        "scss",
        "sql",
        "tsx",
        "typescript",
        "terraform",
        "hcl",
      },
    },
  },
}
